# Generated by Django 4.0 on 2021-12-18 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_no', models.CharField(max_length=9, unique=True)),
                ('name', models.TextField(max_length=2000, null=True)),
                ('batch', models.DateField()),
                ('otp', models.TextField(max_length=6, null=True)),
                ('otp_timeout', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.TextField(max_length=2000)),
                ('course_code', models.TextField(max_length=6)),
                ('course_period', models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter')], default='Summer', max_length=8)),
                ('course_year', models.DateField()),
                ('course_type', models.CharField(choices=[('PC', 'Program Core'), ('PE', 'Program Elective'), ('OE', 'Open Elective'), ('M', 'Minors'), ('IR', 'Institute Requirement'), ('LR', 'Labratory Requirement')], default='PC', max_length=4)),
                ('no_of_classes', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('minimum_attendance_percentage', models.FloatField(default=0.75)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=2000)),
                ('message', models.TextField(max_length=2000, null=True)),
                ('date_of_sending', models.DateTimeField()),
                ('file_link', models.TextField(null=True)),
                ('receiver_id', models.IntegerField()),
                ('receiver_type', models.TextField(choices=[('D', 'Department'), ('C', 'Course'), ('S', 'Section')], default='C', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('status', models.TextField(choices=[('S', 'Suspended'), ('M', 'Modified'), ('A', 'Active')], default='A', max_length=2)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='attendance_manager.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.TextField(max_length=2)),
                ('batch', models.DateField()),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='attendance_manager.department')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStudents',
            fields=[
                ('course_student_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='attendance_manager.courses')),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='attendance_manager.student')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='department_id',
            field=models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='attendance_manager.department'),
        ),
        migrations.AddField(
            model_name='courses',
            name='section_id',
            field=models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, to='attendance_manager.section'),
        ),
        migrations.CreateModel(
            name='ClassRepresentative',
            fields=[
                ('class_rep_id', models.AutoField(primary_key=True, serialize=False)),
                ('rep_of_id', models.IntegerField()),
                ('rep_of_type', models.TextField(choices=[('C', 'Course'), ('S', 'Section')], default='C', max_length=2)),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='attendance_manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('present_status', models.BooleanField(default=False)),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='attendance_manager.student')),
                ('timetable_id', models.ForeignKey(db_column='timetable_id', on_delete=django.db.models.deletion.CASCADE, to='attendance_manager.timetable')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='department_id',
            field=models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.DO_NOTHING, to='attendance_manager.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='section_id',
            field=models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.DO_NOTHING, to='attendance_manager.section'),
        ),
    ]
