# Generated by Django 4.0 on 2021-12-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='section_id',
            field=models.ForeignKey(blank=True, db_column='section_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='attendance_manager.section'),
        ),
    ]
